# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(764, 528)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 30, 421, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.cookie = QtWidgets.QTextEdit(Dialog)
        self.cookie.setGeometry(QtCore.QRect(240, 100, 491, 81))
        self.cookie.setObjectName("cookie")
        self.Status = QtWidgets.QTextEdit(Dialog)
        self.Status.setGeometry(QtCore.QRect(240, 190, 491, 231))
        self.Status.setObjectName("Status")
        self.Start = QtWidgets.QPushButton(Dialog)
        self.Start.setGeometry(QtCore.QRect(480, 450, 93, 28))
        self.Start.setObjectName("Start")
        self.Pause = QtWidgets.QPushButton(Dialog)
        self.Pause.setGeometry(QtCore.QRect(620, 450, 93, 28))
        self.Pause.setObjectName("Pause")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(90, 110, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(50, 280, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(440, 490, 201, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Cancel Friend Request Script By PhCtrlZ"))
        self.label.setText(_translate("Dialog", "Script hủy lời mời kết bạn"))
        self.Start.setText(_translate("Dialog", "Bắt đầu"))
        self.Pause.setText(_translate("Dialog", "Tạm dừng"))
        self.label_2.setText(_translate("Dialog", "Nhập cookie:"))
        self.label_3.setText(_translate("Dialog", "Status(Trạng thái):"))
        self.label_4.setText(_translate("Dialog", "Service was created by PhCtrlZ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
